### ISSUE TITLE
`DEPRECATION: Using this.$() in a component has been deprecated, consider using this.element`

### ISSUE THREAD

**Issue by alexdiliberto** [RSSchermer/ember-spectrum-color-picker#30]
Deprecation being thrown [on](https://github.com/RSSchermer/ember-spectrum-color-picker/blob/0.9.0/addon/components/spectrum-color-picker.js#L61) [these](https://github.com/RSSchermer/ember-spectrum-color-picker/blob/0.9.0/addon/components/spectrum-color-picker.js#L65) [five](https://github.com/RSSchermer/ember-spectrum-color-picker/blob/0.9.0/addon/components/spectrum-color-picker.js#L69) [lines](https://github.com/RSSchermer/ember-spectrum-color-picker/blob/0.9.0/addon/components/spectrum-color-picker.js#L152) [here](https://github.com/RSSchermer/ember-spectrum-color-picker/blob/0.9.0/addon/components/spectrum-color-picker.js#L162) as a result of [this commit](https://github.com/emberjs/ember-jquery/pull/153) from the latest 1.1.0 version of `@ember/jquery`

**Comment by RSSchermer** [comment]
Should be fixed on 0.9.1, could you verify this resolves your issue?

**Comment by alexdiliberto** [comment]
@RSSchermer Hey thanks for the quick response! I was still seeing some deprecations and opened [this PR](https://github.com/RSSchermer/ember-spectrum-color-picker/pull/31)

**Comment by alexdiliberto** [comment]
Fixed by https://github.com/RSSchermer/ember-spectrum-color-picker/pull/31
